name: Fast Ubuntu GUI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Desktop & Fast VNC
        run: |
          sudo apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install -y xfce4 desktop-base xfce4-terminal dbus-x11 tigervnc-standalone-server novnc websockify

      - name: Configure and Start GUI
        run: |
          mkdir -p ~/.vnc
          echo "123456" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd

          cat << 'EOF' > ~/.vnc/xstartup
          #!/bin/sh
          unset SESSION_MANAGER
          unset DBUS_SESSION_BUS_ADDRESS
          dbus-launch --exit-with-session startxfce4 &
          EOF
          chmod +x ~/.vnc/xstartup

          # បើក TigerVNC ដោយប្រើ 16-bit depth ដើម្បីបង្កើនល្បឿនរលូន
          vncserver :1 -geometry 1280x720 -depth 16 -localhost no

          # បើក NoVNC Web
          websockify -D --web=/usr/share/novnc/ 6080 localhost:5901

      - name: Start Cloudflare Tunnel
        run: |
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb
          nohup cloudflared tunnel --url http://localhost:6080 > cf.log 2>&1 &
          sleep 6

          CF_URL=$(grep -o 'https://[-a-zA-Z0-9@:%._\+~#=]\+trycloudflare\.com' cf.log | head -n 1)
          echo "================================================================"
          echo "ចុច Link នេះដើម្បីចូល GUI: ${CF_URL}/vnc.html?autoconnect=true"
          echo "Password: 123456"
          echo "================================================================"

      - name: Keep Alive
        run: |
          sleep 21600
