name: Ubuntu Web GUI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install XFCE and NoVNC
        run: |
          sudo apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install -y xfce4 desktop-base xscreensaver xfce4-terminal tightvncserver novnc websockify

      - name: Start VNC Server
        run: |
          mkdir -p ~/.vnc
          echo "123456" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          vncserver :1 -geometry 1280x720 -depth 24
          websockify -D --web=/usr/share/novnc/ 6080 localhost:5901

      - name: Start Cloudflare Tunnel
        run: |
          # ទាញយក cloudflared
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb
          
          # បើកដំណើរការ Tunnel ទៅកាន់ Port NoVNC
          nohup cloudflared tunnel --url http://localhost:6080 > cloudflare.log 2>&1 &
          
          # រង់ចាំយក Public URL
          sleep 6
          echo "================================================================"
          grep -o 'https://[-a-zA-Z0-9@:%._\+~#=]\+trycloudflare\.com' cloudflare.log | head -n 1
          echo "================================================================"
          echo "Password VNC គឺ: 123456"

      - name: Keep Alive
        run: |
          sleep 21600
